[package]
name = "viennetta-gb"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
bitflags = "2.4.2"
libc = "0.2.152"
log = "0.4.20"

[dependencies.rust-libretro]
version = "0.3.1"
features = [ "unstable-env-commands" ]
