[package]
name = "screen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linuxfb = "0.3.1"
viennetta_gb = { path = "../viennetta_gb" }